name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn test
      env:
        SUPER_SECRET: ${{ secrets.SuperSecret }}
        APP_ENV: testing
        LEAN_CLOUD_APP_ID: ${{ secrets.LEAN_CLOUD_APP_ID }}
        LEAN_CLOUD_APP_KEY: ${{ secrets.LEAN_CLOUD_APP_KEY }}
        LEAN_CLOUD_SERVER_URLS: ${{ secrets.LEAN_CLOUD_SERVER_URLS }}